name: tiktok_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.10.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.0.14
  get: ^4.6.5
  image_picker: ^1.1.2
  timeago: ^3.1.1
  video_compress: ^3.1.2
  video_player: ^2.5.3
  google_fonts: ^6.2.1
  image_cropper: ^7.0.5
  emoji_choose: ^0.0.2
  geoflutterfire2: ^2.3.15
  shared_preferences: ^2.0.0
  geolocator: ^9.0.2
  share_plus: ^7.2.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
